services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    environment:
      - DEFAULT_EMAIL=${ACME_EMAIL}

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_REGISTRY_AUTH=true

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/certs
      o: bind
  html:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/html
      o: bind
  acme:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/acme
      o: bind

networks:
  proxy:
    external: true
    name: proxy
